---
Parameters:
  ProjectName:
    Type: String
  Region:
    Type: String
  User:
    Type: String

Resources:
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /

  BuildRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref ProjectName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - codebuild:*
          - codecommit:*
          - logs:Create*
          - logs:Put*
          - ecr:BatchCheckLayerAvailability,
          - ecr:CompleteLayerUpload,
          - ecr:GetAuthorizationToken,
          - ecr:InitiateLayerUpload,
          - ecr:PutImage,
          - ecr:UploadLayerPart
          - ecr:GetAuthorizationToken
          Resource: '*'
      Roles:
      - !Ref BuildRole

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Description: Test whether the word "Congratulations" exists in index.html
      ServiceRole: !GetAtt BuildRole.Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref ProjectName
          - Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: latest
      Source:
        Type: CODECOMMIT
        Location: !Join ['', ['https://git-codecommit.', !Ref Region, '.amazonaws.com/v1/repos/', !Ref ProjectName ]]
      SourceVersion: refs/heads/master
      TimeoutInMinutes: 10

  # ECR repo to use with this tutorial: https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
  # Copy files from lab-files/docker-sample-codebuild into the git repo and build the CodeBuild project.
  ImageRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Join ["", ["arn:aws:iam::", !Ref AWS::AccountId, ":user/", !Ref User]]
          Action:
            - "ecr:GetDownloadUrlForLayer"
            - "ecr:BatchGetImage"
            - "ecr:BatchCheckLayerAvailability"
            - "ecr:PutImage"
            - "ecr:InitiateLayerUpload"
            - "ecr:UploadLayerPart"
            - "ecr:CompleteLayerUpload"
