---
Parameters:
  RepoName:
    Type: String

Resources:
  RepoUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: repo-user
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"
      UserName: repo-user

  RepoUserJrDev:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: deny-master-merge
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action:
                  - codecommit:GitPush
                  - codecommit:DeleteBranch
                  - codecommit:PutFile
                  - codecommit:MergeBranchesByFastForward
                  - codecommit:MergeBranchesBySquash
                  - codecommit:MergeBranchesByThreeWay
                  - codecommit:MergePullRequestByFastForward
                  - codecommit:MergePullRequestBySquash
                  - codecommit:MergePullRequestByThreeWay
                Resource: arn:aws:codecommit:*:*:*
                Condition:
                  StringEqualsIfExists:
                    codecommit:References:
                      - refs/heads/master
                  'Null':
                    codecommit:References: 'false'

        - PolicyName: repo-user-jr-dev
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"
      UserName: repo-user-jr-dev

  RepoUpdates:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: "ccliver@gmail.com"
        Protocol: email

  Repo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryDescription: Repo for DevOps Pro certification lab
      Triggers:
      - Name: RepoUpdates
        CustomData: testing
        DestinationArn: !Ref RepoUpdates
        Branches:
        - master
        Events:
        - all
